name: Continuous Integration

on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [adopt@1.17, adopt@1.11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version; ${{ matrix.java-version }}
        run: sbt -v +test