name: Build

on:
  push:
  pull_request:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run test and coverage
        run: sbt +test
      ### Release part
      - name: Publish on Codacy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: target/scala-2.13/coverage-report/cobertura.xml
      - name: Tag release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: sbt ciReleaseTagNextVersion
    ### If completed, this workflow trigger deploy.yaml
