name: Build

on:
  push:
  pull_request:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run test and coverage
        run: sbt +test
      ### Release part
      - name: Tag release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: sbt ciReleaseTagNextVersion
    ### If completed, this workflow trigger deploy.yaml
